name = "colored"
version = "1.0.2"

description = "Simple CLI color library for gleam"
licences = ["MIT"]
repository = { type = "github", user = "dhruvdabhi101", repo = "colored" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
